name: Deploy
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd frontend && npm install && npm run build
      - run: scp -r frontend/dist/* root@213.226.112.41:/opt/visage_site/frontend/dist/